import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

def send_email(jobs, sender_email, sender_password, receiver_email):
    if not jobs:
        return

    subject = "🚀 New Internship Opportunities Found!"
    
    # Summary
    total_jobs = len(jobs)
    summary = f"<p><strong>Total New Internships:</strong> {total_jobs}</p>"

    # Styled job entries
    body = """
    <html>
    <head>
    <style>
        .job-card {
            border: 1px solid #ccc;
            border-radius: 10px;
            padding: 12px;
            margin-bottom: 20px;
            background-color: #f9f9f9;
        }
        .job-card h3 {
            color: #007BFF;
            margin: 0;
        }
        .button {
            display: inline-block;
            padding: 6px 12px;
            background-color: #007BFF;
            color: white;
            text-decoration: none;
            border-radius: 5px;
        }
        .footer {
            font-size: 0.9em;
            color: #666;
            margin-top: 30px;
        }
    </style>
    </head>
    <body>
        <h2>🎯 Filtered Internships Matching Your Interests</h2>
        """ + summary

    for i, job in enumerate(jobs, 1):
        title = job.get("title", "N/A")
        org = job.get("organization") or job.get("company", "N/A")
        loc = job.get("location", "N/A")
        stipend = job.get("stipend", "N/A")
        link = job.get("link", "#")
        source = job.get("source", "N/A")

        body += f"""
        <div class="job-card">
            <h3>#{i}. {title}</h3>
            <p><strong>🏢 Organization:</strong> {org}</p>
            <p><strong>📍 Location:</strong> {loc}</p>
            <p><strong>💰 Stipend:</strong> {stipend}</p>
            <p><strong>🌐 Source:</strong> {source}</p>
            <a href="{link}" class="button" target="_blank">View Internship</a>
        </div>
        """

    body += """
        <div class="footer">
            <p>This email was generated by your Internship Hunting Agent 🧠🤖</p>
            <p>Good luck!</p>
        </div>
    </body>
    </html>
    """

    # Prepare email message
    msg = MIMEMultipart("alternative")
    msg["From"] = sender_email
    msg["To"] = receiver_email
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "html"))

    try:
        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(sender_email, sender_password)
        server.send_message(msg)
        server.quit()
        print("✅ Email sent successfully.")
    except Exception as e:
        print("❌ Failed to send email:", e)
